INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta 2 Rin 26 pulgadas', 'Jeep', 1, 1, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta 2 Rin 26 pulgadas', 'Scoop', 2, 1, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta 2 Rin 26 pulgadas', 'Fratta', 3, 1, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta 2 Rin 26 pulgadas', 'Scorpion', 4, 1, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta 2 Rin 26 pulgadas', 'Storm', 5, 1, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta 2 baltoro Rin 29 pulgadas', 'Jeep', 1, 2, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta 2 baltoro Rin 29 pulgadas', 'Scoop', 2, 2, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta 2 baltoro Rin 29 pulgadas', 'Jeep', 3, 2, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta 2 baltoro Rin 29 pulgadas', 'Scorpion', 4, 2, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta 2 baltoro Rin 29 pulgadas', 'Storm', 5, 2, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta Fat 2 aluminio Rin 29 pulgadas', 'Jeep', 1, 3, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta Fat 2 aluminio Rin 29 pulgadas', 'Scoop', 2, 3, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta Fat 2 aluminio Rin 29 pulgadas', 'Jeep', 3, 3, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta Fat 2 aluminio Rin 29 pulgadas', 'Scorpion', 4, 3, CURRENT_TIMESTAMP, 10);
INSERT INTO BICYCLEENTITY (DESCRIPTION, "NAME", BRAND_ID, CATEGORY_ID, CREATIONDATE, STOCK) 
	VALUES ('Bicicleta Fat 2 aluminio Rin 29 pulgadas', 'Storm', 5, 3, CURRENT_TIMESTAMP, 10);
