INSERT INTO APP.cliententity (ADDRESS,EMAIL,FIRSTNAME,IDAUTH0,LASTNAME,LOGIN,PHONE) 
VALUES ('Cra 109','test@test.com','test','599a05f785b13252e7f4a3cf' ,'test@test.com', 'test@test.com', '1234556');

INSERT INTO APP.SHOPPINGENTITY (DATEOFPURCHASE, "NAME", STATUS, TOTALPRICE, CLIENT_ID) 
	VALUES ('2016-11-16 06:43:19.77', NULL, 'PROCESO', 120000.0, 1);
INSERT INTO APP.SHOPPINGENTITY (DATEOFPURCHASE, "NAME", STATUS, TOTALPRICE, CLIENT_ID) 
	VALUES ('2017-11-16 06:43:19.77', NULL, 'PAGADO', 150000.0, 1);

INSERT INTO APP.ITEMSHOPPINGENTITY ("NAME", QUANTITY, TEMPUSER, SHOPPING_ID, BICYCLE_ID) 
	VALUES ('bici', 1, 'test@test.com', 1, 1);
INSERT INTO APP.ITEMSHOPPINGENTITY ("NAME", QUANTITY, TEMPUSER, SHOPPING_ID, BICYCLE_ID) 
	VALUES ('bici grande', 1, 'test@test.com', 2, 2);
INSERT INTO APP.ITEMSHOPPINGENTITY ("NAME", QUANTITY, TEMPUSER, SHOPPING_ID, BICYCLE_ID) 
	VALUES ('Muchas bicis', 2, 'test@test.com', 2, 3);